[package]
name = "malloc_size_of"
version = "1.1.8"
authors = ["The Servo Project Developers", "Thomas Krause <thomaskrause@posteo.de>"]
license = "MIT"
description = "This is a fork of the `malloc_size_of` crate, which is part of the Servo codebase,"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["euclid", "serde", "smallvec", "hashbrown", "hibitset"]


[dependencies]
euclid =  { version = "0.22.6", optional = true}
serde = { version = "1.0.27", optional = true }
serde_bytes = { version = "0.10", optional = true }
smallbitvec = {version = "2.1.0", optional = true }
smallvec = {version = "0.6", optional = true }
string_cache = { version = "0.7", optional = true }
time = { version = "0.1.17", optional = true }
url = { version = "1.2", optional = true }
void = { version = "1.0.2", optional = true }
hashbrown = { version="0.11", optional = true }
hibitset = { version = "0.6.3", optional = true }
winapi = { version ="0.3.9", features=['heapapi']}